import {Experience} from '@/components/Experience';
import {Hero,Briefing,Breach} from '@/components/Story';
import CrewSelector from '@/components/CrewSelector';
import {PhaseOne,Escape} from '@/components/Phases';
import {Elimination} from '@/components/Elimination';
import Vault from '@/components/Vault';
import CrewId from '@/components/CrewId';
import {Rules,Timeline,Venue,Closing} from '@/components/Details';
import {event} from '@/config/event';
export default function Page(){const schema={'@context':'https://schema.org','@type':'Event',name:event.name,description:'A heist-themed technology event. Forty-five crews of three. INR 25,000 in prizes.',startDate:event.starts,endDate:event.ends,eventStatus:'https://schema.org/EventScheduled',eventAttendanceMode:'https://schema.org/OfflineEventAttendanceMode',location:{'@type':'Place',name:event.venue,address:{'@type':'PostalAddress',streetAddress:'Bhaktivedanta Swami Marg, Vile Parle (West)',addressLocality:'Mumbai',addressRegion:'Maharashtra',addressCountry:'IN'}},organizer:{'@type':'Organization',name:'DJS CODEAI',url:event.instagram},...(event.siteUrl?{url:event.siteUrl,image:`${event.siteUrl}/media/social.jpg`}:{})};return <Experience><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><main id="operation"><Hero/><div className="facts-strip"><span><b>45</b> CREWS</span><span><b>03</b> PER CREW</span><span><b>10</b> HOURS</span><span><b>01</b> MINT</span><span className="red">NO SECOND CHANCES.</span></div><Briefing/><CrewSelector/><Breach/><PhaseOne/><Elimination/><Escape/><Vault/><section id="loot" className="loot section"><div className="section-index"><span>THE PAYOFF</span><span>INVENTORY / ₹25,000</span></div><div className="loot-title"><h2>High stakes.<br/><em>Higher rewards.</em></h2><p>Not just bragging rights.<br/>Something worth getting out for.</p></div><div className="prize-lineup">{[['01','12,000','FIRST CREW OUT'],['02','8,000','SECOND CREW OUT'],['03','5,000','THIRD CREW OUT']].map(([n,value,label])=><div key={n} className="prize"><span className="prize-rank">{n}</span><span className="mono">{label}</span><strong>₹{value}</strong><span className="prize-trophy">+ TROPHY</span></div>)}</div><p className="certificate">EVERY OPERATIVE LEAVES WITH AN E-CERTIFICATE.</p></section><CrewId/><Rules/><Timeline/><Venue/>{event.sponsors.length>0&&<section className="section"><h2>The financiers.</h2><div className="sponsors">{event.sponsors.map(s=><a key={s.name} href={s.url}><img src={s.logo} alt={s.name} width="160" height="80"/></a>)}</div></section>}{event.organizers.length>0&&<section className="section"><h2>The masterminds.</h2><div className="organizers">{event.organizers.map(o=><article key={o.name}><img src={o.photo} alt={o.name} width="240" height="280"/><span>{o.codename}</span><h3>{o.name}</h3><p>{o.role}</p></article>)}</div></section>}<Closing/></main></Experience>;}
