'use client';
import {useRef,useState} from 'react';
import {Download,RefreshCw,Share2,Fingerprint,ArrowUpRight,Check} from 'lucide-react';
import {codenames,shareMessage} from '@/config/event';
import {share} from './Experience';
export default function CrewId(){const [name,setName]=useState('');const [identity,setIdentity]=useState<{name:string;code:string;id:string}|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const card=useRef<HTMLDivElement>(null);
 function assign(){const clean=name.trim();if(!clean){setMessage('Your name is required to issue a crew ID.');return;}const pool=codenames.filter(c=>c!==identity?.code);const values=crypto.getRandomValues(new Uint32Array(2));setIdentity({name:clean,code:pool[values[0]%pool.length],id:`CV2-1009-${values[1].toString(16).slice(-4).toUpperCase()}`});setMessage('Clearance granted. Your crew ID is ready.');}
 async function makeCard(){if(!identity)return null;await document.fonts.ready;const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=760;const c=canvas.getContext('2d')!;c.fillStyle='#111615';c.fillRect(0,0,1200,760);c.strokeStyle='#35413c';c.lineWidth=2;c.strokeRect(30,30,1140,700);c.fillStyle='#e33c30';c.fillRect(30,30,1140,10);c.fillStyle='#a4b2a7';c.font='20px "IBM Plex Mono",monospace';c.fillText('PERSONNEL DATABASE / OPERATION CODEVERSE',70,100);c.fillText('CREW FILE',70,165);c.fillStyle='#f4f0e6';c.font='bold 100px "Barlow Condensed",sans-serif';c.fillText(identity.code.toUpperCase(),65,285);c.fillStyle='#a4b2a7';c.font='18px "IBM Plex Mono",monospace';c.fillText('OPERATIVE NAME',70,355);c.fillStyle='#f4f0e6';let size=38;c.font=`${size}px "IBM Plex Mono",monospace`;while(c.measureText(identity.name).width>950&&size>18){size--;c.font=`${size}px "IBM Plex Mono",monospace`;}c.fillText(identity.name,70,410);c.fillStyle='#a4b2a7';c.font='22px "IBM Plex Mono",monospace';c.fillText(identity.id,70,480);c.fillStyle='#c0d0ab';c.fillText('CLEARANCE: AUTHORIZED',70,535);for(let i=0;i<58;i++){c.fillStyle=i%3?'#c6cbb9':'#111615';c.fillRect(75+i*5,590,2+(i%2),65);}c.font='18px "IBM Plex Mono",monospace';c.fillStyle='#c6cbb9';c.fillText('09.10.2026 / DJSCE MUMBAI',600,620);c.fillText('@DJSCODEAI / SOUVENIR ID',600,655);try{const logo=new Image();logo.src='/media/codeai-original.png';await logo.decode();c.drawImage(logo,90,380,930,280,865,105,250,75);}catch{}return new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));}
 async function download(){setBusy(true);try{const blob=await makeCard();if(!blob)throw Error();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`codeverse-${identity!.code.toLowerCase()}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setMessage('Crew ID downloaded. Send it to your people.');}catch{setMessage('Could not export the ID. Please try again.');}finally{setBusy(false);}}
 async function shareCard(){if(!identity)return;setBusy(true);try{const blob=await makeCard();if(blob&&navigator.canShare){const file=new File([blob],`codeverse-${identity.code}.png`,{type:'image/png'});if(navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'CodeVerse Crew ID',text:`${identity.code}, reporting for duty. ${shareMessage}`});setMessage('Shared.');return;}}setMessage(await share(`${identity.code}, reporting for duty. ${shareMessage}`));}catch(e){if((e as Error).name!=='AbortError')setMessage('Sharing is unavailable. Download your ID instead.');}finally{setBusy(false);}}
 return <section id="identity" className="identity section"><div className="section-index"><span>PERSONNEL DATABASE</span><span>LOCAL CLEARANCE ONLY</span></div><div className="identity-layout"><div><h2>Leave your name.<br/><em>Take a codename.</em></h2><p>Every great heist starts with a new identity.<br/>Find out who you are on the job.</p><form onSubmit={e=>{e.preventDefault();assign();}}><label htmlFor="operative-name">YOUR NAME</label><div className="identity-input"><input id="operative-name" value={name} onChange={e=>setName(e.target.value)} maxLength={50} placeholder="e.g. Aarav Mehta" autoComplete="name" required/><button className="icon-button" aria-label="Assign codename" type="submit"><ArrowUpRight/></button></div><button className="button" type="submit">{identity?'Roll again':'Assign codename'}{identity?<RefreshCw size={15}/>:<Fingerprint size={18}/>}</button></form><p className="privacy-note">Made in your browser. Nothing is uploaded.<br/>A souvenir, not a registration or entry pass.</p><p className="feedback" role="status">{message}</p></div><div className="id-preview-wrap"><div ref={card} className="id-card" data-sc-tilt="6"><div className="id-card-top"><span>CODEAI / CREW FILE</span><Fingerprint size={32}/></div><small>OPERATION CODEVERSE</small><h3>{identity?.code || 'CLASSIFIED'}</h3><div className="id-name"><small>OPERATIVE NAME</small><span>{identity?.name || 'YOUR NEXT IDENTITY'}</span></div><div className="id-data"><span>{identity?.id || 'CV2-1009-XXXX'}</span><b>{identity?<><Check size={13}/>AUTHORIZED</>:'AWAITING ASSIGNMENT'}</b></div><div className="id-card-bottom"><div className="barcode"/><span>09.10.2026<br/>DJSCE · MUMBAI<br/>@DJSCODEAI</span></div></div><div className="id-tools"><button disabled={!identity||busy} onClick={download}><Download size={16}/>Download ID</button><button disabled={!identity||busy} onClick={shareCard}><Share2 size={16}/>Share</button></div></div></div></section>;
}
