import {ArrowDown,ArrowUpRight,ArrowRight,Fingerprint,Radio} from 'lucide-react';
import {JoinButton} from './Experience';
export function Hero(){return <section id="home" className="hero" data-sc-act="pin" data-sc-span="2.15"><div data-sc-stage className="hero-stage" data-sc-spotlight>
 <div className="hero-environment"><img className="hero-image" src="/media/hero.webp" alt="Three crew members in red approach a monumental steel vault" fetchPriority="high" width="1536" height="1024"/></div><div className="hero-scrim"/><div className="hero-orbit" aria-hidden="true"><i/><i/><i/></div><div className="hero-steel" aria-hidden="true"/><div className="hero-dust" aria-hidden="true"/>
 <div className="hero-content"><div className="hero-kicker"><span className="red-line"/>DJS CODEAI PRESENTS <span className="small-cross">[ RECRUITMENT FILE 002 ]</span></div><h1>CODEVERSE<span className="edition">2.0</span><em>THE HEIST</em></h1><p>Forty-five crews of three.<br/>One mint. No second chances.</p><div className="hero-actions"><JoinButton/><a className="text-button" href="#briefing">Discover the operation <ArrowDown size={16}/></a></div></div>
 <div className="hero-operative"><img src="/media/operative.webp" alt="A masked operative in a crimson hood" width="900" height="1350" fetchPriority="high"/></div><div className="hero-foreground-fade"/><div className="hero-side-note" aria-hidden="true">NO NAMES. NO PASTS. JUST THE PLAN.</div><div className="hero-coordinate"><span>OPERATION CV2—0910</span><span>19°06′ N / 72°50′ E</span><span className="red">CLASSIFIED / LEVEL 03</span></div>
 <div className="hero-bottom"><div className="event-date"><b>09</b><span>OCTOBER 2026<br/>DJSCE · MUMBAI</span></div><div className="hero-bottom-center"><span className="red-dot"/>THE PROFESSOR IS RECRUITING</div><a href="#briefing" className="scroll-cue">SCROLL TO BREAK IN <ArrowDown size={15}/></a></div>
 <div className="hero-ticket" aria-hidden="true"><small>RESTRICTED ACCESS</small><strong>CV—02</strong><span>09 / 10 / 2026</span></div>
 </div></section>;}
export function Briefing(){return <section id="briefing" className="briefing section" data-sc-act="flow"><div className="section-index"><span>01 / THE BRIEFING</span><span>TRANSMISSION RECEIVED <Radio size={14}/></span></div><div className="briefing-layout"><div className="briefing-visual"><img src="/media/briefing.webp" alt="The Professor’s planning table with blueprints, photographs and a red string route" width="1536" height="1024" loading="lazy"/><div className="evidence-caption"><span>EXHIBIT A / THE PLAN</span><span>FARMHOUSE · FIVE MONTHS AGO</span></div><div className="dossier-slip" data-sc-tilt="5"><Fingerprint size={31}/><span>NO NAMES.<br/>NO PASTS.</span><b>JUST THE PLAN.</b></div></div><div className="briefing-copy"><p className="mono muted">A MESSAGE FROM THE PROFESSOR</p><h2>This is not<br/>a hackathon.<br/><em>It’s a heist.</em></h2><p>It’s been five months since he found you. No names. No pasts. Just a knock on the door, and a man who called himself <strong>The Professor.</strong></p><p>He trained you. No phones. No families. No room for error. Today, the training ends. <strong>Today, you go in.</strong></p><blockquote>“The plan is only as good as the crew executing it.”<cite>THE PROFESSOR</cite></blockquote><a className="text-button" href="#crew">Find your people <ArrowRight size={17}/></a></div></div><div className="mission-statement"><span>YOUR OBJECTIVE</span><p>Get in. Take control.<br/>Print your future. <em>Get out.</em></p><span className="mission-mark" aria-hidden="true">↳</span></div></section>;}
export function Breach(){return <section className="breach" data-sc-act="pin" data-sc-span="1.5"><div data-sc-stage className="breach-stage"><div className="corridor" aria-hidden="true">{[0,1,2,3,4].map(n=><i key={n} style={{'--n':n} as React.CSSProperties}/>)}</div><div className="breach-photo" aria-hidden="true"/><div className="breach-door door-left"/><div className="breach-door door-right"/><div className="breach-copy"><span className="mono red">BREACH PROTOCOL / AUTHORIZED</span><h2>YOU’RE<br/><em>IN.</em></h2><p>The training ends here.</p></div><div className="laser"/></div></section>;}
