'use client';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';
export default function Vault(){const mount=useRef<HTMLDivElement>(null);const section=useRef<HTMLElement>(null);useEffect(()=>{
 const host=mount.current!,act=section.current!;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;host.appendChild(renderer.domElement);host.classList.add('has-webgl');
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.1,70);camera.position.set(.4,.15,10.3);camera.lookAt(0,0,0);
 const textureCanvas=document.createElement('canvas');textureCanvas.width=512;textureCanvas.height=512;const tc=textureCanvas.getContext('2d')!;tc.fillStyle='#888888';tc.fillRect(0,0,512,512);let seed=23;const random=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};for(let i=0;i<16000;i++){const v=Math.floor(90+random()*80);tc.strokeStyle=`rgba(${v},${v},${v},.2)`;tc.beginPath();const y=random()*512;const x=random()*512;tc.moveTo(x,y);tc.lineTo(x+random()*100,y);tc.stroke();}const texture=new THREE.CanvasTexture(textureCanvas);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(3,3);
 const steel=new THREE.MeshStandardMaterial({color:0x596367,metalness:.83,roughness:.43,roughnessMap:texture,bumpMap:texture,bumpScale:.035});const edge=new THREE.MeshStandardMaterial({color:0xa3aaa9,metalness:.9,roughness:.24});const dark=new THREE.MeshStandardMaterial({color:0x202629,metalness:.7,roughness:.5});const red=new THREE.MeshStandardMaterial({color:0xc53628,metalness:.4,roughness:.5});
 const all=new THREE.Group();scene.add(all);const rim=new THREE.Mesh(new THREE.TorusGeometry(2.52,.23,24,100),steel);all.add(rim);const innerRim=new THREE.Mesh(new THREE.TorusGeometry(2.28,.085,16,100),edge);innerRim.position.z=.12;all.add(innerRim);
 const wall=new THREE.Mesh(new THREE.RingGeometry(2.5,30,96),dark);wall.position.z=-.3;all.add(wall);
 const pivot=new THREE.Group();pivot.position.set(-2.35,0,.18);all.add(pivot);const door=new THREE.Group();door.position.x=2.35;pivot.add(door);
 const disk=new THREE.Mesh(new THREE.CylinderGeometry(2.28,2.28,.38,96),steel);disk.rotation.x=Math.PI/2;door.add(disk);
 [2.13,1.85,1.18].forEach((r,i)=>{const t=new THREE.Mesh(new THREE.TorusGeometry(r,i===2?.045:.065,12,96),i===1?dark:edge);t.position.z=.23;door.add(t);});
 const wheel=new THREE.Group();wheel.position.z=.62;door.add(wheel);const wheelRing=new THREE.Mesh(new THREE.TorusGeometry(.67,.065,16,64),edge);wheel.add(wheelRing);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.21,.21,.27,32),dark);hub.rotation.x=Math.PI/2;wheel.add(hub);
 for(let i=0;i<6;i++){const a=i*Math.PI/3;const rod=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,1.35,12),edge);rod.rotation.z=a;wheel.add(rod);}
 const bolts:THREE.Mesh[]=[];for(let i=0;i<12;i++){const a=i*Math.PI/6;const bolt=new THREE.Mesh(new THREE.BoxGeometry(.4,.14,.15),edge);bolt.position.set(Math.cos(a)*2.08,Math.sin(a)*2.08,.3);bolt.rotation.z=a;door.add(bolt);bolts.push(bolt);const rivet=new THREE.Mesh(new THREE.SphereGeometry(.045,8,8),edge);rivet.position.set(Math.cos(a)*2.52,Math.sin(a)*2.52,.24);all.add(rivet);}
 for(const y of [-1.35,1.35]){const hinge=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,.7,20),dark);hinge.position.set(-2.36,y,.36);all.add(hinge);}
 const plate=new THREE.Mesh(new THREE.BoxGeometry(.7,.22,.035),red);plate.position.set(0,1.47,.28);door.add(plate);
 scene.add(new THREE.HemisphereLight(0xe4eff1,0x16110e,2.4));const key=new THREE.DirectionalLight(0xd9eaff,5);key.position.set(1,3,4);scene.add(key);const warm=new THREE.PointLight(0xe75230,35,14);warm.position.set(-3,-1,4);scene.add(warm);const fill=new THREE.PointLight(0xf1ddab,40,12);fill.position.set(2,1,2);scene.add(fill);
 let visible=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)');function render(){if(!visible&&!reduced.matches)return;const p=reduced.matches?1:Number(act.style.getPropertyValue('--sc-p')||0);const unlock=Math.min(1,p/.36);const open=THREE.MathUtils.smoothstep(p,.27,.9);wheel.rotation.z=unlock*Math.PI*1.25;pivot.rotation.y=-open*2.05;bolts.forEach((bolt,i)=>{const a=i*Math.PI/6;const r=2.08-unlock*.18;bolt.position.x=Math.cos(a)*r;bolt.position.y=Math.sin(a)*r;});all.rotation.y=-.1+p*.1;camera.position.z=(10.3-open*.9)*(innerWidth<768?1.25:1);renderer.render(scene,camera);host.setAttribute('data-sc-verify-state',`door:${pivot.rotation.y.toFixed(2)};wheel:${wheel.rotation.z.toFixed(2)}`);}
 const resize=()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();render();};const ro=new ResizeObserver(resize);ro.observe(host);const mo=new MutationObserver(render);mo.observe(act,{attributes:true,attributeFilter:['style']});const io=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)render();},{rootMargin:'150px'});io.observe(host);reduced.addEventListener('change',render);resize();return()=>{ro.disconnect();mo.disconnect();io.disconnect();reduced.removeEventListener('change',render);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();}});[steel,edge,dark,red].forEach(m=>m.dispose());texture.dispose();renderer.dispose();renderer.domElement.remove();};
 },[]);
 return <><div className="vault-prelude"><span className="mono">THE JOB WAS NEVER ABOUT GETTING IN.</span><p>It was about<br/><em>getting out.</em></p><div className="red-thread"/></div><section ref={section} id="vault" className="vault" data-sc-act="pin" data-sc-span="2.8"><div data-sc-stage className="vault-stage"><div className="vault-head"><span className="mono">VAULT 0910 / SECURITY LEVEL 03</span><span className="mono red">SCROLL TO UNLOCK</span></div><div className="vault-interior" aria-hidden="true"/><div className="vault-reward"><span className="mono">ACCESS GRANTED</span><strong>₹25,000</strong><p>THE LOOT IS YOURS TO TAKE.</p></div><div className="vault-canvas" ref={mount} role="img" aria-label="A massive steel vault. Scrolling retracts the bolts, turns the wheel and opens the door."><div className="vault-fallback"><div className="fallback-wheel">✣</div></div></div><div className="vault-bottom"><span>MECHANICAL LOCK / CV—2.0</span><div className="lock-progress"><i/><i/><i/><i/><i/></div><span>THE PROFESSOR’S FINAL MOVE</span></div></div></section></>;
}
