import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import sharp from 'sharp';
const browser=await chromium.launch({channel:'chrome',headless:true});
const failures=[],errors=[],results=[];const url=process.env.TEST_URL||'http://localhost:3000';
const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});
await context.addInitScript(()=>{sessionStorage.setItem('cv-entered','1');Element.prototype.requestPointerLock=()=>{};Element.prototype.setPointerCapture=()=>{};});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);
async function check(name,fn){try{await fn();results.push(name);console.log('PASS',name);}catch(e){failures.push({name,error:e.message});console.log('FAIL',name,e.message);}}
async function position(selector,p=0){await page.locator(selector).evaluate((el,p)=>window.scrollTo({top:el.getBoundingClientRect().top+scrollY+Math.max(0,el.clientHeight-innerHeight)*p,behavior:'instant'}),p);await page.waitForTimeout(180);}
await check('semantic SEO content',async()=>{assert.equal(await page.locator('h1').count(),1);assert.match(await page.title(),/CodeVerse 2.0/);const data=JSON.parse(await page.locator('script[type="application/ld+json"]').textContent());assert.equal(data.startDate,'2026-10-09T08:00:00+05:30');});
await check('operation menu opens, traps focus and Escape closes',async()=>{await page.getByRole('button',{name:'Operation menu'}).click();assert.equal(await page.locator('dialog').evaluate(e=>e.open),true);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').evaluate(e=>e.open),false);});
await check('crew size accepts duo and trio',async()=>{await position('#crew');await page.getByRole('button',{name:/THE DUO/}).click();assert.match(await page.locator('#crew [role=status]').textContent(),/DUO CLEARED/);await page.getByRole('button',{name:'Add optional third operative'}).click();assert.match(await page.locator('#crew [role=status]').textContent(),/TRIO CLEARED/);});
await check('45 to 10 is driven by real scroll',async()=>{await position('.elimination',0);assert.equal(await page.locator('.roster-grid .active').count(),45);await position('.elimination',1);assert.equal(await page.locator('.roster-grid .active').count(),10);});
await check('vault has three distinct mechanical scroll states',async()=>{const states=[];for(const p of [0,.5,1]){await position('#vault',p);await page.waitForTimeout(120);states.push(await page.locator('.vault-canvas').getAttribute('data-sc-verify-state'));assert.ok(Math.abs(await page.locator('.vault-stage').evaluate(e=>e.getBoundingClientRect().top))<2,'Vault must remain pinned and visible');await page.screenshot({path:`artifacts/vault-${p}.png`});}assert.equal(new Set(states).size,3);assert.ok(states.every(Boolean));});
await check('escape rail travels horizontally',async()=>{await position('#escape',0);const a=await page.locator('.map-rail').evaluate(e=>getComputedStyle(e).transform);await position('#escape',1);const b=await page.locator('.map-rail').evaluate(e=>getComputedStyle(e).transform);assert.notEqual(a,b);});
await check('crew ID assigns, rerolls and downloads a real PNG',async()=>{await position('#identity');await page.getByLabel('YOUR NAME',{exact:true}).fill('Shivansh Vyas');await page.getByRole('button',{name:'Assign codename',exact:true}).last().click();const first=await page.locator('.id-card h3').textContent();assert.notEqual(first,'CLASSIFIED');await page.getByRole('button',{name:'Roll again',exact:true}).click();assert.notEqual(await page.locator('.id-card h3').textContent(),first);const wait=page.waitForEvent('download');await page.getByRole('button',{name:'Download ID',exact:true}).click();const file=await wait;await file.saveAs('artifacts/crew-id.png');const meta=await sharp('artifacts/crew-id.png').metadata();assert.equal(meta.width,1200);assert.equal(meta.height,760);});
await check('rulebook panels and FAQ expose correct copy',async()=>{await position('#rules');await page.getByRole('tab',{name:/Your equipment/}).click();assert.match(await page.getByRole('tabpanel').textContent(),/laptop charger/);await page.getByRole('tab',{name:/Qualification/}).click();assert.match(await page.getByRole('tabpanel').textContent(),/first crew to collect every hint/);await page.getByText('Can beginners join?',{exact:true}).click();assert.ok(await page.locator('details').filter({hasText:'Can beginners join?'}).getAttribute('open')!==null);});
await check('download links return PDF and calendar files',async()=>{for(const [path,type] of [['/documents/codeverse-rulebook.pdf','application/pdf'],['/documents/codeverse.ics','text/calendar']]){const r=await context.request.get(url+path);assert.equal(r.status(),200);assert.ok((await r.body()).length>100);}const r=await context.request.get(url+'/documents/codeverse.ics');assert.match(await r.text(),/20261009T023000Z/);});
await check('sound starts off, toggles only with user action',async()=>{await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));const button=page.getByRole('button',{name:'Turn sound on'});assert.equal(await button.getAttribute('aria-pressed'),'false');await button.click();assert.equal(await page.getByRole('button',{name:'Turn sound off'}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Turn sound off'}).click();});
for(const [width,height] of [[1920,1080],[1440,900],[1366,768],[1024,900],[768,1024],[430,932],[390,844]]){await check(`layout and media at ${width}px`,async()=>{await page.setViewportSize({width,height});await page.goto(url,{waitUntil:'networkidle'});await page.screenshot({path:`artifacts/hero-${width}.png`});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);const bad=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.loading!=='lazy'&&(!i.complete||!i.naturalWidth)).map(i=>i.src));assert.deepEqual(bad,[]);});}
await check('mobile all sections fit horizontally',async()=>{for(const id of ['#briefing','#crew','#plan','#escape','#loot','#identity','#rules','#schedule','#venue','#join']){await position(id);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,id);await page.screenshot({path:`artifacts/mobile-${id.slice(1)}.png`});}});
await check('reduced-motion removes pins and preserves route and loot',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await page.reload({waitUntil:'networkidle'});const heights=await page.locator('[data-sc-act="pin"]').evaluateAll(els=>els.map(e=>({h:e.clientHeight,stage:e.querySelector('[data-sc-stage]').clientHeight})));assert.ok(heights.every(x=>Math.abs(x.h-x.stage)<3));await position('#escape');assert.equal(await page.locator('.map-rail').evaluate(e=>getComputedStyle(e).transform),'none');await page.screenshot({path:'artifacts/reduced-escape.png'});await position('#vault');await page.screenshot({path:'artifacts/reduced-vault.png'});});
await check('no browser exceptions',async()=>assert.deepEqual(errors,[]));
await fs.writeFile('artifacts/verification.json',JSON.stringify({passed:results,failures,errors},null,2));
await browser.close();if(failures.length)process.exitCode=1;
